#!/usr/bin/env bash
#
# Provision the local headless browser used by the kernel's web_search tool.
#
# Reads apps/sidecar/config/browser-binary.json for the pinned snapshot + sha256,
# downloads the platform-matching binary into apps/sidecar/.runtime/browser/, and
# writes LIGHTPANDA into apps/sidecar/env/.env.local (gitignored) so the kernel
# SDK picks it up on next boot without polluting the tracked .env.development
# with each contributor's home-dir path. LIGHTPANDA is the SDK's native env
# var; we set it directly with no translation layer. Idempotent: re-runs are
# no-ops when sha256 matches.
#
# Migration: removes any legacy LIGHTPANDA / WEB_SEARCH_BROWSER_PATH lines
# from .env.development so the two never coexist.
#
# Usage: just install-browser     (or)     bash apps/sidecar/scripts/install-browser.sh

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
api_root="$(cd -- "$script_dir/.." >/dev/null 2>&1 && pwd)"
config_file="$api_root/config/browser-binary.json"
runtime_dir="$api_root/.runtime/browser"
env_file="$api_root/env/.env.local"
tracked_env="$api_root/env/.env.development"

if [[ ! -f "$config_file" ]]; then
    echo "[install-browser] config not found: $config_file" >&2
    exit 1
fi

require() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "[install-browser] missing required command: $1" >&2
        exit 1
    fi
}

require jq
require curl
if command -v shasum >/dev/null 2>&1; then
    sha256_cmd=(shasum -a 256)
elif command -v sha256sum >/dev/null 2>&1; then
    sha256_cmd=(sha256sum)
else
    echo "[install-browser] need shasum or sha256sum to verify the download" >&2
    exit 1
fi

uname_s="$(uname -s)"
uname_m="$(uname -m)"
case "$uname_s" in
    Darwin) os="darwin" ;;
    Linux)  os="linux" ;;
    *) echo "[install-browser] unsupported OS: $uname_s" >&2; exit 1 ;;
esac
case "$uname_m" in
    arm64|aarch64) arch="arm64" ;;
    x86_64|amd64)  arch="x64" ;;
    *) echo "[install-browser] unsupported arch: $uname_m" >&2; exit 1 ;;
esac
platform="${os}-${arch}"

snapshot="$(jq -r '.snapshot' "$config_file")"
url="$(jq -r --arg p "$platform" '.platforms[$p].url // empty' "$config_file")"
sha="$(jq -r --arg p "$platform" '.platforms[$p].sha256 // empty' "$config_file")"
if [[ -z "$url" || -z "$sha" ]]; then
    echo "[install-browser] platform '$platform' is not pinned in $config_file" >&2
    exit 1
fi

mkdir -p "$runtime_dir"
target="$runtime_dir/lightpanda"

verify_sha() {
    local file="$1" expected="$2"
    local actual
    actual="$("${sha256_cmd[@]}" "$file" | awk '{print $1}')"
    [[ "$actual" == "$expected" ]]
}

if [[ -f "$target" ]] && verify_sha "$target" "$sha"; then
    echo "[install-browser] $platform lightpanda already pinned to $snapshot at $target"
else
    tmp="$(mktemp -t lightpanda.XXXXXX)"
    cleanup() { rm -f "$tmp"; }
    trap cleanup EXIT
    echo "[install-browser] downloading $platform lightpanda ($snapshot)"
    curl -fL --retry 3 --connect-timeout 15 -o "$tmp" "$url"
    if ! verify_sha "$tmp" "$sha"; then
        actual="$("${sha256_cmd[@]}" "$tmp" | awk '{print $1}')"
        echo "[install-browser] sha256 mismatch for $url" >&2
        echo "                  expected: $sha" >&2
        echo "                  actual:   $actual" >&2
        echo "                  Upstream nightly probably moved — bump apps/sidecar/config/browser-binary.json." >&2
        exit 1
    fi
    mv "$tmp" "$target"
    chmod +x "$target"
    trap - EXIT
    echo "[install-browser] installed $target"
fi

# Migrate: strip LIGHTPANDA / legacy WEB_SEARCH_BROWSER_PATH from the tracked
# .env.development so contributor-specific paths never get committed. The
# loader (api-env.ts) overrides .env.development with .env.local, so the new
# pin in .env.local wins anyway, but we keep the tracked file clean.
if [[ -f "$tracked_env" ]]; then
    if grep -qE '^(LIGHTPANDA|WEB_SEARCH_BROWSER_PATH)=' "$tracked_env"; then
        awk '/^(LIGHTPANDA|WEB_SEARCH_BROWSER_PATH)=/ { next } { print }' "$tracked_env" >"$tracked_env.tmp"
        mv "$tracked_env.tmp" "$tracked_env"
        echo "[install-browser] stripped LIGHTPANDA/WEB_SEARCH_BROWSER_PATH from tracked $tracked_env"
    fi
fi

# Patch .env.local (gitignored) so the kernel SDK picks it up automatically.
if [[ ! -f "$env_file" ]]; then
    printf '# Local-only overrides. Generated by apps/sidecar/scripts/install-browser.sh.\n# Not committed; safe to delete and regenerate.\n' >"$env_file"
fi
if grep -q '^LIGHTPANDA=' "$env_file"; then
    if ! grep -q "^LIGHTPANDA=${target}$" "$env_file"; then
        awk -v path="$target" '
            /^LIGHTPANDA=/ { print "LIGHTPANDA=" path; next }
            { print }
        ' "$env_file" >"$env_file.tmp"
        mv "$env_file.tmp" "$env_file"
        echo "[install-browser] updated LIGHTPANDA in $env_file"
    fi
else
    printf 'LIGHTPANDA=%s\n' "$target" >>"$env_file"
    echo "[install-browser] appended LIGHTPANDA to $env_file"
fi
