packages:
  - apps/*
  - packages/agent-planning
  - packages/lark
  - packages/ocr
  - packages/ooxml
  - packages/wechat
verifyDepsBeforeRun: false
shamefullyHoist: true
strictPeerDependencies: false
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@swc/core'
  - core-js
  - cpu-features
  - msgpackr-extract
  - protobufjs
  - ssh2
  - vue-demi
