packages:
  - apps/*
  - packages/agent-planning
  - packages/lark
  - packages/ocr
  - packages/ooxml
verifyDepsBeforeRun: false
shamefullyHoist: true
strictPeerDependencies: false
allowBuilds:
  '@biomejs/biome': true
  '@nestjs/core': true
  '@scarf/scarf': false
  '@swc/core': true
  core-js: true
  cpu-features: true
  msgpackr-extract: true
  protobufjs: true
  ssh2: true
  vue-demi: true
