/**
 * Bridge between the planner's `Chain` data model and the OS workflow engine's
 * `WorkflowDefinitionSpec`. Round-trippable: chainFromGraph(chainToGraph(c)) ≈ c
 * for chains produced by the planner itself.
 */
import type {
    WorkflowDefinitionSpec,
    WorkflowEdgeDefinition,
    WorkflowNodeDefinition,
} from '../workflow-definition.types';
import type {
    AgentAssignment,
    Chain,
    TaskContract,
    TaskMetadata,
    TaskRecord,
    TaskView,
} from './schemas';
import { ChainStatus } from './schemas';
import { sha256Json } from './hashing';

const CONTRACT_DATA_KEY = '_serialChainContract';
const PLANNER_PROVENANCE_KEY = '_planner';

const NODE_X_STEP = 240;
const NODE_Y = 80;

interface PersistedContract {
    inputs: string[];
    outputs: string[];
    success_criteria: string[];
    constraints: string[];
    agents: AgentAssignment[];
    locked: boolean;
    view_hash: string;
    contract_hash: string;
}

interface PersistedPlannerMeta {
    version: number;
    chain_id: string;
    chain_version: number;
    revision_id: string | null;
    revision_counter: number;
    expected_final_outputs: string[];
    original_prompt: string;
    conversation_summary: string;
}

/**
 * Convert a verified Chain to a WorkflowDefinitionSpec ready for the OS engine.
 *
 * Frames the chain with canonical `start` / `end` nodes so the graph passes the
 * orchestration agent's structural validator (single start, single end, all
 * nodes reachable from start, every path can reach end) AND so the open-platform
 * canvas — which can only render `start` / `end` / `agent` — has the framing
 * nodes it expects. Reachability is preserved by chaining tasks linearly:
 *   start → t1 → t2 → … → tN → end
 *
 * Planner provenance is stashed on the `start` node's data; `readProvenance`
 * already prefers reading from there so {@link chainFromGraph} round-trips.
 * Empty chains still emit a `start → end` skeleton so downstream code never has
 * to special-case "missing framing".
 */
export function chainToGraph(chain: Chain): WorkflowDefinitionSpec {
    const taskCount = chain.records.length;
    const startNode: WorkflowNodeDefinition = {
        id: 'start',
        type: 'start',
        name: '开始',
        data: { [PLANNER_PROVENANCE_KEY]: makeProvenance(chain) },
        position: { x: 0, y: NODE_Y },
    };
    const endNode: WorkflowNodeDefinition = {
        id: 'end',
        type: 'end',
        name: '结束',
        data: {},
        position: { x: (taskCount + 1) * NODE_X_STEP, y: NODE_Y },
    };

    const nodes: WorkflowNodeDefinition[] = [startNode];
    const edges: WorkflowEdgeDefinition[] = [];

    chain.records.forEach((record, index) => {
        nodes.push(taskRecordToNode(record, index));
    });
    nodes.push(endNode);

    // start → t1 → … → tN → end (or start → end when chain is empty)
    if (taskCount === 0) {
        edges.push({ id: 'e-start-end', sourceNodeId: 'start', targetNodeId: 'end' });
    } else {
        edges.push({
            id: `e-start-${chain.records[0]!.task_id}`,
            sourceNodeId: 'start',
            targetNodeId: chain.records[0]!.task_id,
        });
        for (let i = 0; i < taskCount - 1; i++) {
            edges.push({
                id: `e${i + 1}`,
                sourceNodeId: chain.records[i]!.task_id,
                targetNodeId: chain.records[i + 1]!.task_id,
            });
        }
        edges.push({
            id: `e-${chain.records[taskCount - 1]!.task_id}-end`,
            sourceNodeId: chain.records[taskCount - 1]!.task_id,
            targetNodeId: 'end',
        });
    }

    const lastTaskId = chain.records[taskCount - 1]?.task_id;
    return {
        nodes,
        edges,
        outputs: lastTaskId
            ? chain.expected_final_outputs.map((output) => ({
                  name: output,
                  expression: `\${${lastTaskId}.output.${output}}`,
              }))
            : chain.expected_final_outputs.map((output) => ({ name: output })),
    };
}

/** Restore a Chain from a graph generated by `chainToGraph`. Lossy outside that round-trip. */
export function chainFromGraph(graph: WorkflowDefinitionSpec): Chain {
    const taskNodes = graph.nodes.filter((node) => node.type !== 'start' && node.type !== 'end');
    const records: TaskRecord[] = taskNodes.map((node, index) => nodeToTaskRecord(node, index));
    const provenance = readProvenance(graph, taskNodes);

    return {
        chain_id: provenance.chain_id,
        version: provenance.chain_version,
        status: ChainStatus.Draft,
        records,
        repair_trace: [],
        expected_final_outputs: provenance.expected_final_outputs,
        original_prompt: provenance.original_prompt,
        current_revision_id: provenance.revision_id,
        revision_counter: provenance.revision_counter,
        conversation_summary: provenance.conversation_summary,
    };
}

/** Collect locked agents from the graph (used during repair to preserve user choices). */
export function collectLockedAgents(graph: WorkflowDefinitionSpec): Set<string> {
    const locked = new Set<string>();
    for (const node of graph.nodes) {
        if (node.type === 'start' || node.type === 'end') continue;
        const contract = readContract(node);
        const agentLocked = Boolean(node.locked || node.assignment?.locked || contract?.locked);
        if (!agentLocked) continue;
        if (contract) {
            for (const agent of contract.agents) locked.add(agent.agent);
        }
        if (node.assignment?.targetId) locked.add(node.assignment.targetId);
    }
    return locked;
}

// ────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ────────────────────────────────────────────────────────────────────────────

function taskRecordToNode(record: TaskRecord, index: number): WorkflowNodeDefinition {
    const persisted: PersistedContract = {
        inputs: [...record.contract.inputs],
        outputs: [...record.contract.outputs],
        success_criteria: [...record.contract.success_criteria],
        constraints: [...record.contract.constraints],
        agents: record.contract.agents.map((agent) => ({ ...agent })),
        locked: record.metadata.locked,
        view_hash: record.metadata.view_hash,
        contract_hash: record.metadata.contract_hash,
    };

    const primaryAgent = record.contract.agents[0];
    const node: WorkflowNodeDefinition = {
        id: record.task_id,
        type: 'agent',
        name: record.view.title,
        description: record.view.description,
        executionOrder: index + 1,
        locked: record.metadata.locked,
        data: {
            requirement: record.view.requirement,
            description: record.view.description,
            success_criteria: persisted.success_criteria,
            constraints: persisted.constraints,
            outputs: outputSchemaFromContract(record.contract),
            [CONTRACT_DATA_KEY]: persisted,
        },
        position: { x: (index + 1) * NODE_X_STEP, y: NODE_Y },
    };

    if (primaryAgent) {
        node.assignment = {
            targetKind: 'package',
            targetId: primaryAgent.agent,
            selectionPolicy: record.metadata.locked ? 'locked' : 'recommended',
            locked: record.metadata.locked,
            requiredCapabilities: derivedCapabilities(record.contract),
        };
    }

    return node;
}

function nodeToTaskRecord(node: WorkflowNodeDefinition, index: number): TaskRecord {
    const contract = readContract(node);
    const view: TaskView = {
        task_id: node.id,
        title: node.name?.trim() || `任务 ${index + 1}`,
        description: stringFromData(node.data, 'description', node.description ?? `任务 ${index + 1}`),
        requirement: stringFromData(node.data, 'requirement', `完成 ${node.name ?? '任务'} 的目标`),
    };

    const restoredContract: TaskContract = contract
        ? {
              task_id: node.id,
              inputs: [...contract.inputs],
              outputs: [...contract.outputs],
              success_criteria: [...contract.success_criteria],
              constraints: [...contract.constraints],
              agents: contract.agents.map((agent) => ({ ...agent })),
          }
        : {
              task_id: node.id,
              inputs: [],
              outputs: [],
              success_criteria: [],
              constraints: [],
              agents: [],
          };

    const metadata: TaskMetadata = {
        version: 1,
        view_hash: contract?.view_hash ?? sha256Json(view),
        contract_hash: contract?.contract_hash ?? sha256Json(restoredContract),
        locked: contract?.locked ?? Boolean(node.locked || node.assignment?.locked),
        created_by: 'planner',
        last_modified_by: 'system',
    };

    return { task_id: node.id, view, contract: restoredContract, metadata };
}

function readContract(node: WorkflowNodeDefinition): PersistedContract | null {
    const candidate = node.data?.[CONTRACT_DATA_KEY];
    if (!candidate || typeof candidate !== 'object') return null;
    const value = candidate as Partial<PersistedContract>;
    if (
        !Array.isArray(value.inputs) ||
        !Array.isArray(value.outputs) ||
        !Array.isArray(value.success_criteria) ||
        !Array.isArray(value.constraints) ||
        !Array.isArray(value.agents)
    ) {
        return null;
    }
    return {
        inputs: value.inputs.map(String),
        outputs: value.outputs.map(String),
        success_criteria: value.success_criteria.map(String),
        constraints: value.constraints.map(String),
        agents: value.agents
            .filter((agent): agent is AgentAssignment => Boolean(agent) && typeof agent === 'object')
            .map((agent) => ({
                order: Number(agent.order) || 0,
                agent: String(agent.agent),
                responsibility: String(agent.responsibility ?? ''),
            })),
        locked: Boolean(value.locked),
        view_hash: String(value.view_hash ?? ''),
        contract_hash: String(value.contract_hash ?? ''),
    };
}

function readProvenance(
    graph: WorkflowDefinitionSpec,
    taskNodes: WorkflowNodeDefinition[],
): PersistedPlannerMeta {
    const carrier =
        graph.nodes.find((node) => node.type === 'start' && node.data?.[PLANNER_PROVENANCE_KEY]) ??
        taskNodes.find((node) => node.data?.[PLANNER_PROVENANCE_KEY]);
    const candidate = carrier?.data?.[PLANNER_PROVENANCE_KEY];
    if (candidate && typeof candidate === 'object') {
        const value = candidate as Partial<PersistedPlannerMeta>;
        return {
            version: Number(value.version) || 1,
            chain_id: String(value.chain_id ?? 'chain_external'),
            chain_version: Number(value.chain_version) || 1,
            revision_id: typeof value.revision_id === 'string' ? value.revision_id : null,
            revision_counter: Number(value.revision_counter) || 0,
            expected_final_outputs: Array.isArray(value.expected_final_outputs)
                ? value.expected_final_outputs.map(String)
                : [],
            original_prompt: String(value.original_prompt ?? ''),
            conversation_summary: String(value.conversation_summary ?? ''),
        };
    }
    return {
        version: 1,
        chain_id: 'chain_external',
        chain_version: 1,
        revision_id: null,
        revision_counter: 0,
        expected_final_outputs: graph.outputs?.map((o) => o.name) ?? [],
        original_prompt: '',
        conversation_summary: '',
    };
}

function makeProvenance(chain: Chain): PersistedPlannerMeta {
    return {
        version: 1,
        chain_id: chain.chain_id,
        chain_version: chain.version,
        revision_id: chain.current_revision_id,
        revision_counter: chain.revision_counter,
        expected_final_outputs: [...chain.expected_final_outputs],
        original_prompt: chain.original_prompt,
        conversation_summary: chain.conversation_summary,
    };
}

function outputSchemaFromContract(contract: TaskContract): Record<string, unknown> {
    const outputs: Record<string, unknown> = {};
    for (const output of contract.outputs) {
        outputs[output] = { type: 'string', description: 'planner-generated artifact' };
    }
    return outputs;
}

function derivedCapabilities(contract: TaskContract): string[] {
    return Array.from(
        new Set(
            contract.agents
                .map((agent) => agent.agent)
                .concat(contract.outputs)
                .filter(Boolean),
        ),
    );
}

function stringFromData(
    data: Record<string, unknown> | undefined,
    key: string,
    fallback: string,
): string {
    const value = data?.[key];
    if (typeof value === 'string' && value.trim().length > 0) return value;
    return fallback;
}
